### PR TITLE
Updated mainnet authset docs

### PR DESCRIPTION
**Pull request by nklomp**
Updated documentation including testnet docker config changes and certificate/key clarifications

### CODE REVIEW

**Comment by nklomp** [comment]
Sorry @pincombe. Didn't see your PRs that also changed some of the stuff in my PR. Since my PR is more complete about the issues you also changed I think we need to discard them

**Comment by pincombe** [comment]
Your docs still tell users to install v5.0.0-alpine. I think we should update them to either say v5.1.1-alpine or latest. Particularly because otherwise new users will be vulenerable to the Pokemon bug.

**Comment by nklomp** [comment]
Hmzz, might have missed some stuff. Let me check

**Comment by pincombe** [comment]
I think Paul was going to check the behavior of latest to ensure it does what is expected. That would probably be the ideal approach as then we wouldn't need to update the documentation so frequently.

Something to maybe follow up with Paul in future?

**Comment by nklomp** [comment]
Yeah that would be preferable yes. Updated it to 5.1.1. Sorry for the confusion. Updated the 110 Doc to 5.1.1

**Comment by carryforward** [comment]
Good updates.  Much appreciated @nklomp

**Pull request merged**
